# Generated by Django 5.2.6 on 2025-09-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='available_days',
            field=models.JSONField(blank=True, default=list, help_text='List of available days'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'New to teaching (0-1 years)'), ('intermediate', 'Some experience (1-3 years)'), ('experienced', 'Experienced (3-5 years)'), ('expert', 'Highly experienced (5+ years)')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hourly_rate_range',
            field=models.CharField(blank=True, choices=[('10-20', '$10 - $20 per hour'), ('20-35', '$20 - $35 per hour'), ('35-50', '$35 - $50 per hour'), ('50-75', '$50 - $75 per hour'), ('75-100', '$75 - $100 per hour'), ('100+', '$100+ per hour')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('early_morning', 'Early Morning (6:00 AM - 9:00 AM)'), ('morning', 'Morning (9:00 AM - 12:00 PM)'), ('afternoon', 'Afternoon (12:00 PM - 5:00 PM)'), ('evening', 'Evening (5:00 PM - 8:00 PM)'), ('night', 'Night (8:00 PM - 11:00 PM)'), ('flexible', 'Flexible')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='teaching_mode',
            field=models.CharField(blank=True, choices=[('online', 'Online Only'), ('in_person', 'In-Person Only'), ('both', 'Both Online & In-Person')], max_length=20),
        ),
    ]
